TypeError: __init__() got an unexpected keyword argument 'providing_args'
 - Installed later version of Allauth (solved)

django.core.exceptions.ImproperlyConfigured: allauth.account.middleware.AccountMiddleware must be added to settings.MIDDLEWARE
    -Addes information to settings.MIDDLEWARE (solved)